CategoryGroup.create([{
        "id"=>1,
        "name"=>"Home & QOL",
        "configuration_id"=>nil
    },
    {
        "id"=>2,
        "name"=>"Food & Dining",
        "configuration_id"=>nil
    },
    {
        "id"=>3,
        "name"=>"Cash & ATM",
        "configuration_id"=>nil
    },
    {
        "id"=>4,
        "name"=>"Income",
        "configuration_id"=>nil
    },
    {
        "id"=>5,
        "name"=>"Health & Fitness",
        "configuration_id"=>nil
    },
    {
        "id"=>6,
        "name"=>"Entertainment",
        "configuration_id"=>nil
    },
    {
        "id"=>7,
        "name"=>"Housing",
        "configuration_id"=>nil
    },
    {
        "id"=>8,
        "name"=>"Transportation",
        "configuration_id"=>nil
    },
    {
        "id"=>9,
        "name"=>"Fees",
        "configuration_id"=>nil
    },
    {
        "id"=>10,
        "name"=>"Transfers",
        "configuration_id"=>nil
    },
    {
        "id"=>11,
        "name"=>"Utilities",
        "configuration_id"=>nil
    },
    {
        "id"=>12,
        "name"=>"Xmas",
        "configuration_id"=>nil
    }
])