CategoryGroupMembership.create([
    {
        "id"=>1,
        "category"=>"Quality of Life",
        "category_group_id"=>1,
        "profile_id"=>nil,
        "configuration_id"=>nil
    },
    {
        "id"=>2,
        "category"=>"Groceries",
        "category_group_id"=>2,
        "profile_id"=>nil,
        "configuration_id"=>nil
    },
    {
        "id"=>3,
        "category"=>"Cash & ATM",
        "category_group_id"=>3,
        "profile_id"=>nil,
        "configuration_id"=>nil
    },
    {
        "id"=>4,
        "category"=>"ATM Fee",
        "category_group_id"=>3,
        "profile_id"=>nil,
        "configuration_id"=>nil
    },
    {
        "id"=>5,
        "category"=>"Income",
        "category_group_id"=>4,
        "profile_id"=>nil,
        "configuration_id"=>nil
    },
    {
        "id"=>6,
        "category"=>"Pharmacy",
        "category_group_id"=>5,
        "profile_id"=>nil,
        "configuration_id"=>nil
    },
    {
        "id"=>7,
        "category"=>"Restaurants",
        "category_group_id"=>2,
        "profile_id"=>nil,
        "configuration_id"=>nil
    },
    {
        "id"=>8,
        "category"=>"Music",
        "category_group_id"=>6,
        "profile_id"=>nil,
        "configuration_id"=>nil
    },
    {
        "id"=>9,
        "category"=>"Mortgage & Rent",
        "category_group_id"=>7,
        "profile_id"=>nil,
        "configuration_id"=>nil
    },
    {
        "id"=>10,
        "category"=>"Shipping",
        "category_group_id"=>1,
        "profile_id"=>nil,
        "configuration_id"=>nil
    },
    {
        "id"=>11,
        "category"=>"Movies & DVDs",
        "category_group_id"=>6,
        "profile_id"=>nil,
        "configuration_id"=>nil
    },
    {
        "id"=>12,
        "category"=>"Food & Dining",
        "category_group_id"=>2,
        "profile_id"=>nil,
        "configuration_id"=>nil
    },
    {
        "id"=>13,
        "category"=>"Health & Fitness",
        "category_group_id"=>5,
        "profile_id"=>nil,
        "configuration_id"=>nil
    },
    {
        "id"=>14,
        "category"=>"Home Insurance",
        "category_group_id"=>7,
        "profile_id"=>nil,
        "configuration_id"=>nil
    },
    {
        "id"=>15,
        "category"=>"Loan Payment",
        "category_group_id"=>7,
        "profile_id"=>nil,
        "configuration_id"=>nil
    },
    {
        "id"=>16,
        "category"=>"Interest Income",
        "category_group_id"=>4,
        "profile_id"=>nil,
        "configuration_id"=>nil
    },
    {
        "id"=>17,
        "category"=>"Paycheck",
        "category_group_id"=>4,
        "profile_id"=>nil,
        "configuration_id"=>nil
    },
    {
        "id"=>18,
        "category"=>"Reimburseable",
        "category_group_id"=>1,
        "profile_id"=>nil,
        "configuration_id"=>nil
    },
    {
        "id"=>19,
        "category"=>"Rental Car & Taxi",
        "category_group_id"=>8,
        "profile_id"=>nil,
        "configuration_id"=>nil
    },
    {
        "id"=>20,
        "category"=>"Public Transportation",
        "category_group_id"=>8,
        "profile_id"=>nil,
        "configuration_id"=>nil
    },
    {
        "id"=>21,
        "category"=>"Shopping",
        "category_group_id"=>1,
        "profile_id"=>nil,
        "configuration_id"=>nil
    },
    {
        "id"=>22,
        "category"=>"Alcohol & Bars",
        "category_group_id"=>2,
        "profile_id"=>nil,
        "configuration_id"=>nil
    },
    {
        "id"=>23,
        "category"=>"Bank Fee",
        "category_group_id"=>9,
        "profile_id"=>nil,
        "configuration_id"=>nil
    },
    {
        "id"=>24,
        "category"=>"Transfer",
        "category_group_id"=>10,
        "profile_id"=>nil,
        "configuration_id"=>nil
    },
    {
        "id"=>25,
        "category"=>"Credit Card Payment",
        "category_group_id"=>10,
        "profile_id"=>nil,
        "configuration_id"=>nil
    },
    {
        "id"=>26,
        "category"=>"Loan Principal",
        "category_group_id"=>7,
        "profile_id"=>nil,
        "configuration_id"=>nil
    },
    {
        "id"=>27,
        "category"=>"Fast Food",
        "category_group_id"=>2,
        "profile_id"=>nil,
        "configuration_id"=>nil
    },
    {
        "id"=>28,
        "category"=>"Electronics & Software",
        "category_group_id"=>1,
        "profile_id"=>nil,
        "configuration_id"=>nil
    },
    {
        "id"=>29,
        "category"=>"Doctor",
        "category_group_id"=>5,
        "profile_id"=>nil,
        "configuration_id"=>nil
    },
    {
        "id"=>30,
        "category"=>"Books",
        "category_group_id"=>6,
        "profile_id"=>nil,
        "configuration_id"=>nil
    },
    {
        "id"=>31,
        "category"=>"Gas & Fuel",
        "category_group_id"=>8,
        "profile_id"=>nil,
        "configuration_id"=>nil
    },
    {
        "id"=>32,
        "category"=>"Hobbies",
        "category_group_id"=>6,
        "profile_id"=>nil,
        "configuration_id"=>nil
    },
    {
        "id"=>33,
        "category"=>"Coffee Shops",
        "category_group_id"=>2,
        "profile_id"=>nil,
        "configuration_id"=>nil
    },
    {
        "id"=>34,
        "category"=>"Home Services",
        "category_group_id"=>1,
        "profile_id"=>nil,
        "configuration_id"=>nil
    },
    {
        "id"=>35,
        "category"=>"Business Services",
        "category_group_id"=>1,
        "profile_id"=>nil,
        "configuration_id"=>nil
    },
    {
        "id"=>36,
        "category"=>"Hotel",
        "category_group_id"=>1,
        "profile_id"=>nil,
        "configuration_id"=>nil
    },
    {
        "id"=>37,
        "category"=>"Entertainment",
        "category_group_id"=>6,
        "profile_id"=>nil,
        "configuration_id"=>nil
    },
    {
        "id"=>38,
        "category"=>"Clothing",
        "category_group_id"=>1,
        "profile_id"=>nil,
        "configuration_id"=>nil
    },
    {
        "id"=>39,
        "category"=>"Financial",
        "category_group_id"=>10,
        "profile_id"=>nil,
        "configuration_id"=>nil
    },
    {
        "id"=>40,
        "category"=>"Mobile Phone",
        "category_group_id"=>11,
        "profile_id"=>nil,
        "configuration_id"=>nil
    },
    {
        "id"=>41,
        "category"=>"Kids",
        "category_group_id"=>1,
        "profile_id"=>nil,
        "configuration_id"=>nil
    },
    {
        "id"=>42,
        "category"=>"Gift",
        "category_group_id"=>1,
        "profile_id"=>nil,
        "configuration_id"=>nil
    },
    {
        "id"=>43,
        "category"=>"Home Improvement",
        "category_group_id"=>1,
        "profile_id"=>nil,
        "configuration_id"=>nil
    },
    {
        "id"=>44,
        "category"=>"Gifts & Donations",
        "category_group_id"=>1,
        "profile_id"=>nil,
        "configuration_id"=>nil
    },
    {
        "id"=>45,
        "category"=>"Internet",
        "category_group_id"=>11,
        "profile_id"=>nil,
        "configuration_id"=>nil
    },
    {
        "id"=>46,
        "category"=>"Newspapers & Magazines",
        "category_group_id"=>6,
        "profile_id"=>nil,
        "configuration_id"=>nil
    },
    {
        "id"=>47,
        "category"=>"Arts",
        "category_group_id"=>6,
        "profile_id"=>nil,
        "configuration_id"=>nil
    },
    {
        "id"=>48,
        "category"=>"Furnishings",
        "category_group_id"=>1,
        "profile_id"=>nil,
        "configuration_id"=>nil
    },
    {
        "id"=>49,
        "category"=>"Pet Food & Supplies",
        "category_group_id"=>1,
        "profile_id"=>nil,
        "configuration_id"=>nil
    },
    {
        "id"=>50,
        "category"=>"Amusement",
        "category_group_id"=>6,
        "profile_id"=>nil,
        "configuration_id"=>nil
    },
    {
        "id"=>51,
        "category"=>"Pets",
        "category_group_id"=>1,
        "profile_id"=>nil,
        "configuration_id"=>nil
    },
    {
        "id"=>52,
        "category"=>"Lawn & Garden",
        "category_group_id"=>1,
        "profile_id"=>nil,
        "configuration_id"=>nil
    },
    {
        "id"=>53,
        "category"=>"Subscriptions",
        "category_group_id"=>6,
        "profile_id"=>nil,
        "configuration_id"=>nil
    },
    {
        "id"=>54,
        "category"=>"Hair",
        "category_group_id"=>5,
        "profile_id"=>nil,
        "configuration_id"=>nil
    },
    {
        "id"=>55,
        "category"=>"Gym",
        "category_group_id"=>5,
        "profile_id"=>nil,
        "configuration_id"=>nil
    },
    {
        "id"=>56,
        "category"=>"Charity",
        "category_group_id"=>1,
        "profile_id"=>nil,
        "configuration_id"=>nil
    },
    {
        "id"=>57,
        "category"=>"Home Supplies",
        "category_group_id"=>1,
        "profile_id"=>nil,
        "configuration_id"=>nil
    },
    {
        "id"=>58,
        "category"=>"Bonus",
        "category_group_id"=>4,
        "profile_id"=>nil,
        "configuration_id"=>nil
    },
    {
        "id"=>59,
        "category"=>"Office Supplies",
        "category_group_id"=>1,
        "profile_id"=>nil,
        "configuration_id"=>nil
    },
    {
        "id"=>60,
        "category"=>"Gas",
        "category_group_id"=>11,
        "profile_id"=>nil,
        "configuration_id"=>nil
    },
    {
        "id"=>61,
        "category"=>"Electricity",
        "category_group_id"=>11,
        "profile_id"=>nil,
        "configuration_id"=>nil
    },
    {
        "id"=>62,
        "category"=>"Books & Supplies",
        "category_group_id"=>6,
        "profile_id"=>nil,
        "configuration_id"=>nil
    },
    {
        "id"=>63,
        "category"=>"Drivers License Fee",
        "category_group_id"=>8,
        "profile_id"=>nil,
        "configuration_id"=>nil
    },
    {
        "id"=>64,
        "category"=>"Xmas",
        "category_group_id"=>12,
        "profile_id"=>nil,
        "configuration_id"=>nil
    },
    {
        "id"=>65,
        "category"=>"Utilities",
        "category_group_id"=>11,
        "profile_id"=>nil,
        "configuration_id"=>nil
    },
    {
        "id"=>66,
        "category"=>"Travel",
        "category_group_id"=>8,
        "profile_id"=>nil,
        "configuration_id"=>nil
    }
])