version: '3'
volumes:
  postgres-data:
services:
  db:
    image: postgres:9.6
    container_name: db
    env_file:
      - .env/development
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports: 
      - "5433:5432"

  mail:
    image: schickling/mailcatcher
    container_name: mailcatcher
    ports:
      - 1080:1080

  web:
    build: .
    stdin_open: true
    tty: true
    container_name: app
    env_file:
      - .env/development
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0' -P /dev/null"
    volumes:
      - .:/myapp
    ports:
      - "3001:3000"
      - "9876:9876"
    depends_on:
      - db

  # webpack-dev-server:
  #   build: .
  #   command: ./bin/webpack-dev-server
  #   container_name: webpack-dev-server
  #   ports: 
  #     - 3035:3035
  #   volumes:
  #     - .:/myapp
  #   env_file:
  #     - .env/development
  #   environment:
  #     - WEBPACKER_DEV_SERVER_HOST=0.0.0.0
